const express = require('express');
const cors = require('cors');
const db = require('./db');
const routes = require('./routes');
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static('public'));
app.use('/', routes(db));
module.exports = app;